# Generated by Django 6.0.2 on 2026-02-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='creatted_at',
            new_name='created_at',
        ),
    ]
