# Generated by Django 6.0.2 on 2026-02-15 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_no', models.CharField(max_length=100)),
                ('purchased_date', models.DateTimeField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_phone', models.CharField(max_length=100)),
                ('supplier_email', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateTimeField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('uploaded_report1', models.ImageField(upload_to='')),
                ('uploaded_report2', models.ImageField(upload_to='')),
                ('uploaded_report3', models.ImageField(upload_to='')),
                ('uploaded_report4', models.ImageField(upload_to='')),
                ('uploaded_report5', models.ImageField(upload_to='')),
                ('additional_notes', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roq', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.consultations')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.medicines')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases_Dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.medicines')),
                ('purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.purchases')),
            ],
        ),
        migrations.AddField(
            model_name='purchases',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.suppliers'),
        ),
    ]
