# Generated by Django 6.0.2 on 2026-02-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_categories_purchases_suppliers_consultations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='brand_name',
        ),
    ]
